version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_container
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=satc@2024  
    ports:
      - "1433:1433"  
    networks:
      - sql_network
    volumes:
      - sql_data:/var/opt/mssql  

networks:
  sql_network:
    driver: bridge

volumes:
  sql_data:
    driver: local
